######################################################################
# Automatically generated by qmake (1.07a) Wed Mar 29 09:09:06 2006
######################################################################

TEMPLATE = app
QT += gui sql network
CONFIG += 
INCLUDEPATH += .

FORMS += test.ui
# Input
HEADERS += test.h SslOverrideHttp.h
SOURCES += main.cpp test.cpp SslOverrideHttp.cpp
